#include "PhysicalMouseBlocker.h"

#ifdef _WIN32

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#include <atomic>

namespace
{
HANDLE hookThreadHandle =
    nullptr;

DWORD hookThreadId =
    0;

std::atomic_bool blockerEnabled{
    false
};

LRESULT CALLBACK physicalMouseHook(
    int code,
    WPARAM message,
    LPARAM data)
{
    if (code < 0)
    {
        return CallNextHookEx(
            nullptr,
            code,
            message,
            data);
    }

    const MSLLHOOKSTRUCT* mouseData =
        reinterpret_cast<const MSLLHOOKSTRUCT*>(
            data);

    if (!mouseData)
    {
        return CallNextHookEx(
            nullptr,
            code,
            message,
            data);
    }

    /*
     * Allow mouse events generated by SendInput.
     */
    if ((mouseData->flags & LLMHF_INJECTED) != 0)
    {
        return CallNextHookEx(
            nullptr,
            code,
            message,
            data);
    }

    /*
     * Suppress physical mouse movement, buttons, and scrolling.
     */
    return 1;
}

DWORD WINAPI mouseHookThread(
    LPVOID readyEventParameter)
{
    HANDLE readyEvent =
        static_cast<HANDLE>(
            readyEventParameter);

    /*
     * Explicitly create the thread's Windows message queue before
     * another thread attempts to send WM_QUIT.
     */
    MSG message;

    PeekMessageW(
        &message,
        nullptr,
        WM_USER,
        WM_USER,
        PM_NOREMOVE);

    HHOOK mouseHook =
        SetWindowsHookExW(
            WH_MOUSE_LL,
            physicalMouseHook,
            GetModuleHandleW(nullptr),
            0);

    blockerEnabled.store(
        mouseHook != nullptr);

    SetEvent(
        readyEvent);

    if (!mouseHook)
    {
        return 1;
    }

    while (GetMessageW(
               &message,
               nullptr,
               0,
               0) > 0)
    {
        TranslateMessage(
            &message);

        DispatchMessageW(
            &message);
    }

    UnhookWindowsHookEx(
        mouseHook);

    blockerEnabled.store(
        false);

    return 0;
}
}

#endif

bool PhysicalMouseBlocker::enable()
{
#ifdef _WIN32
    if (blockerEnabled.load())
    {
        return true;
    }

    if (hookThreadHandle)
    {
        return false;
    }

    HANDLE readyEvent =
        CreateEventW(
            nullptr,
            TRUE,
            FALSE,
            nullptr);

    if (!readyEvent)
    {
        return false;
    }

    hookThreadHandle =
        CreateThread(
            nullptr,
            0,
            mouseHookThread,
            readyEvent,
            0,
            &hookThreadId);

    if (!hookThreadHandle)
    {
        CloseHandle(
            readyEvent);

        hookThreadId =
            0;

        return false;
    }

    const DWORD waitResult =
        WaitForSingleObject(
            readyEvent,
            5000);

    CloseHandle(
        readyEvent);

    if (waitResult != WAIT_OBJECT_0
        || !blockerEnabled.load())
    {
        if (hookThreadId != 0)
        {
            PostThreadMessageW(
                hookThreadId,
                WM_QUIT,
                0,
                0);
        }

        WaitForSingleObject(
            hookThreadHandle,
            INFINITE);

        CloseHandle(
            hookThreadHandle);

        hookThreadHandle =
            nullptr;

        hookThreadId =
            0;

        blockerEnabled.store(
            false);

        return false;
    }

    return true;
#else
    return false;
#endif
}

void PhysicalMouseBlocker::disable()
{
#ifdef _WIN32
    if (!hookThreadHandle)
    {
        blockerEnabled.store(
            false);

        return;
    }

    PostThreadMessageW(
        hookThreadId,
        WM_QUIT,
        0,
        0);

    WaitForSingleObject(
        hookThreadHandle,
        INFINITE);

    CloseHandle(
        hookThreadHandle);

    hookThreadHandle =
        nullptr;

    hookThreadId =
        0;

    blockerEnabled.store(
        false);
#endif
}

bool PhysicalMouseBlocker::isEnabled()
{
#ifdef _WIN32
    return blockerEnabled.load();
#else
    return false;
#endif
}